name: "Vorstellung"
description: "Will Dignazio's Technology, Science, and Project Blog."

author: "Will Dignazio"

url: "http://slackwill.com/"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: willdignazio.github.io
ga_tracking_id: UA-39320049-1
